steps:
  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/fantomimage:$COMMIT_SHA', '-t', 'gcr.io/${PROJECT_ID}/fantomimage:latest', '.']
    env:
    - 'PORT=8080'

  # - id: 'push image 1'
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '-a', 'gcr.io/${PROJECT_ID}/fantomimage']

images:
  - 'gcr.io/${PROJECT_ID}/fantomimage:$COMMIT_SHA'
  - 'gcr.io/${PROJECT_ID}/fantomimage:latest'
