steps:
  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/fantomimage:$COMMIT_SHA', '.']
    env:
    - 'PORT=8080'

  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/fantomimage:$COMMIT_SHA']

images:
  - 'gcr.io/${PROJECT_ID}/fantomimage:$COMMIT_SHA'
